// LOCALHOST 

### get all contacts
GET http://localhost:8080/contacts 

### get contact by Id
GET http://localhost:8080/contacts/63ccb350332739591b04b95e

### create contact
POST  http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Fred",
  "lastName": "Okorio",
  "email": "send2fredokorio@test.com",
  "favoriteColor": "Black",
  "birthday": "23/12/90" 
}


### PUT contact
PUT  http://localhost:8080/contacts/63c36646b5b5786a26c58eaa
Content-Type: application/json

{
  "_id": "63c36646b5b5786a26c58eaa",
  "firstName": "Cassandra",
  "lastName": "Anderson",
  "email": "andersonC@test.com",
  "favoriteColor": "Indigo",
  "birthday": "02/22/95"
}

### DELETE contact
GET http://localhost:8080/contacts/63ccb350332739591b04b95e


// PRODUCTION

### get all contacts
GET https://offs341-02.onrender.com/contacts 

### get contact by Id
GET https://offs341-02.onrender.com/contacts/63c36646b5b5786a26c58ea8

// PRODUCTION

### create contact
POST  https://offs341-02.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Fred",
  "lastName": "Okorio",
  "email": "send2fredokorio@test.com",
  "favoriteColor": "Black",
  "birthday": "23/12/90" 
}


### PUT contact
PUT  https://offs341-02.onrender.com/contacts/63c36646b5b5786a26c58eaa
Content-Type: application/json

{
  "_id": "63c36646b5b5786a26c58eaa",
  "firstName": "Cassandra",
  "lastName": "Anderson",
  "email": "amazingwoman@test.com",
  "favoriteColor": "Indigo",
  "birthday": "02/22/95"
}

### DELETE contact
DELETE  https://offs341-02.onrender.com/contacts/63ccced7e6512360e4dd6989


